learning_log/urls.py
#!usr/bin/env python3
# -*- coding:utf-8 -*-
"""learning_log URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'', include('learning_logs.urls', namespace='learning_logs')),
]

learning_logs/urls.py
#!usr/bin/env python3
# -*- coding:utf-8 -*-

"""定义learning_logs的URL模式"""
from django.conf.urls import url
from .import views
urlpatterns = [
    #主页
    url(r'^$', views.index, name='index'),

    #显示所有的主题
    url(r'^topics/$', views.topics, name='topics'),

    #特定主题的详细页面
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),

    #用于添加新主题的页面
    url(r'^new_topic/$', views.new_topic, name='new_topic'),

    #用于添加新条目的页面
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),

    #用于编辑条目的页面
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),
]

users/urls.py
#!usr/bin/env python3
# -*- coding:utf-8 -*-
"""为应用程序users定义URL模式"""

from django.conf.urls import url
from django.contrib.auth.views import login
from . import views

urlpatterns = [
    #登录页面
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),

    #注销
    url(r'^logout/$', views.logout_view, name='logout'),

    #注册页面
    url(r'^register/$', views.register, name='register'),
]

learning_logs/models.py
#!usr/bin/env python3
# -*- coding:utf-8 -*-

from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    """用户学习的主题"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User)

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text

class Entry(models.Model):
    """学到的有关某个主题的具体知识"""
    topic = models.ForeignKey(Topic)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """返回模型的字符串表示"""
        if len(self.text) <= 50:
            return self.text
        elif len(self.text) > 50:
            return self.text[:50] + "..."

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
#!usr/bin/env python3
# -*- coding:utf-8 -*-

from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cils': 80})}

learning_logs/views.py
#!usr/bin/env python3
# -*- coding:utf-8 -*-

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

# Create your views here.
def index(request):
    """学习笔记的主页"""
    return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
    """显示所有的主题"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    """显示单个主题及其所有的条目"""
    topic = get_object_or_404(Topic, id=topic_id)
    #确认请求的主题属于当前用户
    if topic.owner != request.user:
        raise Http404

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic,'entries':entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    """添加新主题"""
    if request.method != 'POST':
        #未提交数据；创建一个新表单
        form = TopicForm()
    else:
        #POST提交的数据，对数据进行处理
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))

    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """在特定的主题中添加新条目"""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        #未提交数据,创建一个空表单
        form = EntryForm()
    else:
        #POST提交数据，对数据进行处理
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',
                                                args=[topic_id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """编辑既有条目"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        #初次请求。使用当前条目充填表单
        form = EntryForm(instance=entry)
    else:
        #POST提交的数据，对数据进行处理
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
#!usr/bin/env python3
# -*- coding:utf-8 -*-

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def logout_view(request):
    """注销用户"""
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))

def register(request):
    """注册新用户"""
    if request.method != 'POST':
        #显示空的注册表单
        form = UserCreationForm()
    else:
        #处理填好的表单
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # 让用户自动登录，在重定向到主页
            authenticated_user = authenticate(username=new_user.username,
                    password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))
    context = {'form': form }
    return render(request, 'users/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>学习笔记</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}

</head>

<body>
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed"
                data-toggle="collapse" data-target="#navbar"
                aria-expanded="false" aria-contrals="navbar">
            </button>
            <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
                学习笔记</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'learning_logs:topics' %}">主题</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a>你好, {{ user.username }}.</a></li>
                    <li><a href="{% url 'users:logout' %}">注销</a></li>
                {% else %}
                    <li><a href="{% url 'users:register' %}">注册</a></li>
                    <li><a href="{% url 'users:login' %}">登录</a></li>
                {% endif %}
            </ul>
        </div><!--/.nav-collapse-->
    </div>
</nav>

<div class="container">
    <div class="page-header">
        {% block header %}{% endblock header %}
    </div>
    <div>
        {% block content %}{% endblock content %}
    </div>
</div><!-- /container-->

</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>学习笔记</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}

</head>
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
<h2>
    <a href="{% url 'learning_logs:topic' topic.id %}">{{ 主题 }}</a>
</h2>
{% endblock header %}

{% block content %}

<h3>编辑条目:</h3>
<form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post' class="form">

    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
    <h4><button name="submit">保存修改</button></h4>
    {% endbuttons %}
</form>

{% endblock content %}
<html/>

learning_logs/templates/learning_logs/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>学习笔记</title>
</head>
{% extends "learning_logs/base.html" %}

{% block header %}
    <div class="jumbotron">
        <h1>开始你的学习</h1>
    </div>
{% endblock header %}

{% block content %}
    <h2>
        <a href="{% url 'users:register' %}">注册一个账户</a>
        来制作你的学习笔记, 列出你正在学习的主题。
    </h2>
    <h2>
       每当你学习某个主题的新知识时，就对你学到的知识做一个总结。
    </h2>
{% endblock content %}
<html/>

learning_logs/templates/learning_logs/new_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>学习笔记</title>

</head>
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
<h2>
    <a href="{% url 'learning_logs:topic' topic.id %}">{{ 主题 }}</a>
</h2>
<h3>添加一个新条目:</h3>
{% endblock header %}

{% block content %}

<form action="{% url 'learning_logs:new_entry' topic.id %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form%}

    {% buttons %}
    <h4><button name='submit'> 添加条目</button></h4>
    {% endbuttons%}
</form>

{% endblock content %}
<html/>

learning_logs/templates/learning_logs/new_topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>学习笔记</title>
</head>
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>添加一个新主题:</h2>
{% endblock header %}

{% block content %}

<form action="{% url 'learning_logs:new_topic' %}" method='post' class="form">

    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
    <h4><button name="submit" class="btn btn-primary">添加主题</button></h4>
    {% endbuttons %}
</form>

{% endblock content %}
<html/>

learning_logs/templates/learning_logs/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>学习笔记</title>
</head>
{% extends 'learning_logs/base.html' %}

{% block header %}
<h2>{{ 主题 }}</h2>
{% endblock header %}

{% block content %}

<h3>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">添加新条目</a>
</h3>

    {% for entry in entries %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>
                {{ entry.date_added|date:'M d, Y H:i ' }}
                <small>
                <a href="{% url 'learning_logs:edit_entry' entry.id %}">
                    编辑条目</a>
                </small>
            </h3>
        </div>
        {{ entry.text|linebreaks }}
        <div class="panel-body">
        </div><!-- panel -->
    </div>
    {% empty %}
        目前还没有这个主题的条目。
    {% endfor %}

{% endblock content %}
<html/>

learning_logs/templates/learning_logs/topics.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>学习笔记</title>
</head>
{% extends "learning_logs/base.html" %}

{% block header %}
    <h1>主题</h1>
{% endblock header %}

{% block content %}

<ul>
    {% for topic in topics %}
    <li>
        <h3>
        <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
        </h3>
    </li>
    {% empty %}
    <li>目前还没有添加任何主题。</li>
    {% endfor %}
</ul>
<h3><a href="{% url 'learning_logs:new_topic' %}">添加一个新主题:</a></h3>

{% endblock content %}
<html/>

users/templates/users/login.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>登录你的账号</h2>
{% endblock header %}

{% block content %}

<form method="post" action="{% url 'users:login' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
    <button name="submit">登录</button>
    {% endbuttons %}

    <input type="hidden" name="next" value="{% url 'learning_logs:index' %}"/>
</form>

{% endblock content %}

users/templates/users/register.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
<h2>注册你的账号</h2>
{% endblock header %}

{% block content %}

<form method="post" action="{% url 'users:register' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
    <h3><button name="submit">注册</button></h3>
    {% endbuttons %}
    <input type="hidden" name="next" value="{% url 'learning_logs:index' %}"/>
</form>

{% endblock content %}